

val ss = "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">Hi team,&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">We will be starting a new process in support to determine and analyse if an existing customer would renew their subscription. This would be the pilot batch to see if it works and it would be first started with only US region users.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">Once the data for each customer is published here in forums, information will be passed on to PM - Retention teams accordingly for further action.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><b>1) Which users fall under this category?&nbsp;</b><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">We have selected users who are using the Product for more than&nbsp;<b>5 years</b>&nbsp;and their renewal amount is over \$2000 per year. The region which is covered in this are US East, US West, US Central, US MST, Canada. We have around 50 records out of which<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">*&nbsp;<b>Yearly</b>&nbsp;- 17 user records and 14 of them above \$2000. This totals upto&nbsp;<b><i>\$67,011</i></b><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">*&nbsp;<b>Monthly</b>&nbsp;- 32 user records and 2 of them are above \$2000 rest 30 users are below \$1000 renewal amount.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">Break through for monthly<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">2 user count:&nbsp;<i>\$5450</i><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">30 user count (below \$1000):&nbsp;<i>\$ 11,927</i><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">We will only be focusing on \$2000 above for now and only renewals which is coming for this year since this is just the pilot batch.<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><b>2) What do we do in this process?&nbsp;</b><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">We will try to go through the users requests such as tickets or forum posts which we can get hands on (as much as possible). This also includes chat transcript etc. All of this would determine their account health.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">* How many requests has he raised in the current year?<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">* How many feature request has been raised in the current year?<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">* How many have we satisfied the users requirement by providing actual solution or workarounds?&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">* Did we reject all his requests?&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">* How many issues have they raised in the current year?<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">* Escalations<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">* What would be his current status.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">* MICS tracking ( This will determine the usage of modules Task OR Bugs which is used by the user).<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">As of now to get all of these information through Desk will take alot of time and this is why we have selected only few customers with a specific renewal amount.<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">We also have few issues accessing these data as such information sometime are archived and is not possible to get them through CRM and DESK. Faiyaz, is working with the team to get us updates of archived desk tickets.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><b>3) How does this help us?&nbsp;</b><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">We have been going through retention and keeping records of why customers have cancelled each quarter. However, this should provide us more detailed insights and proceed in a way to retain more customers from cancelling which would result in more revenue per year (possibly) or this what we are trying to achieve.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><b>4) Process flow.&nbsp;</b><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">As mentioned in the above blueprint,&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">CRM - Support data analysis - PM Team - PM Feedback - Retention team - Customer.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">We might not be able to save all renewals and we definitely not be able to provide solution for all the customers. However, lets target some of them and make sure they renew by keeping them happy.&nbsp;<br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal; min-height:15px\"><br /></span></span>" +
        "</p>" +
        "<p style=\"margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\"><span style=\"font-family:&quot;Helvetica Neue&quot;\"><span style=\"font-size:13px; margin:0px; font-style:normal; font-variant:normal; font-size-adjust:none; font-weight:normal; font-stretch:normal; line-height:normal\">The process will start taking place shortly.&nbsp;<br /></span></span>" +
        "</p>" +
        "<div>" +
        "    <br />" +
        "</div>"